### PR TITLE
taper slab age at tip 

### PR DESCRIPTION
**Pull request by mibillen**
so underside of slab thins as the min temperature increases to the background temperature.
This should address issue #353.
However, in looking at this there is still an issue with the "background temperature" used for the top side of the slab where is needs to blend into the overriding plate temperature. I will look at this next week.

### CODE REVIEW

**Review by MFraters — APPROVED** [review]
Looks good to me. Could you indent the code and update the test results?

**Comment by mibillen** [comment]
I fixed the indenting and I also fixed the issue with the temperature on the overriding plate - there were temperatures that were less than the surface temperature  in the region where the slab has a very shallow dip. This is because even though there is very little negative heat content going into the top of the slab, the overriding plate temperature is very close to or even less than the minimum temperature of the slab. Therefore, if the overriding plate temperature is less than the minimum slab temperature, then we don't change the temperature there.  There is still small step in the temperature contours (for the same reason... small deltaT requires a large distance to spread out heat content, even when its not that much). I don't see a way around this. To minimize the size of the offset, I recommend making the "min distance top slab" = -100e3 for this shallow segment. 
This is not an issue when there is no overriding plate (see image). 
Screen Shot 2021-10-30 at 5 07 18 PM
Here's my final version with the overriding plate
Screen Shot 2021-10-30 at 5 10 39 PM
e

**Comment by MFraters** [comment]
The negative temperature in the overriding plate is actually something I had noticed but didn't have time to investigate yet. Good to hear that it is now fixed!

The pictures and it also seem to resolve #353. Can you update the test results?

I also think that these fixes are notable enough to add a line to the changelog.md file, so feel free to add a line there in the fixed heading.

**Comment by mibillen** [comment]
I changed the test for cartesian to include an overriding plate and a dipping slab so that I would end up with points above the slab that are colder than the minimum temperature. This meant that I also need to change the location of the test points in the grid file. This was needed to insure all parts of the code are covered. Here are pics of the new test case.
Screen Shot 2021-11-03 at 3 29 26 PM
d
Screen Shot 2021-11-03 at 3 29 41 PM
.

**Comment by MFraters** [comment]
Thanks for fixing the coverage as well!

**Pull request merged**
