### PR TITLE
fix float to int warnings.

### PR DESCRIPTION
**Pull request by MFraters**
fix for issue #123

### CODE REVIEW

**Comment by tjhei** [comment]
```
7
[188/193] Building CXX object CMakeFiles/aspect.dir/contrib/WorldBuilder/source/features/fault.cc.o
../contrib/WorldBuilder/source/features/fault.cc:340:101: warning: implicit conversion turns floating-point number into integer: 'std::map<std::__cxx11::basic_string<char>, double, std::less<std::__cxx11::basic_string<char> >, std::allocator<std::pair<const std::__cxx11::basic_string<char>, double> > >::mapped_type' (aka 'double') to 'std::vector::size_type' (aka 'unsigned long') [-Wfloat-conversion]
          const unsigned int current_section = (unsigned int)std::floor(one_dimensional_coordinates[distance_from_planes["section"]]);
                                                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../contrib/WorldBuilder/source/features/fault.cc:468:101: warning: implicit conversion turns floating-point number into integer: 'std::map<std::__cxx11::basic_string<char>, double, std::less<std::__cxx11::basic_string<char> >, std::allocator<std::pair<const std::__cxx11::basic_string<char>, double> > >::mapped_type' (aka 'double') to 'std::vector::size_type' (aka 'unsigned long') [-Wfloat-conversion]
          const unsigned int current_section = (unsigned int)std::floor(one_dimensional_coordinates[distance_from_planes["section"]]);
                                                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2 warnings generated.
[192/193] Building CXX object CMakeFiles/aspect.dir/contrib/WorldBuilder/source/features/subducting_plate.cc.o
../contrib/WorldBuilder/source/features/subducting_plate.cc:351:101: warning: implicit conversion turns floating-point number into integer: 'std::map<std::__cxx11::basic_string<char>, double, std::less<std::__cxx11::basic_string<char> >, std::allocator<std::pair<const std::__cxx11::basic_string<char>, double> > >::mapped_type' (aka 'double') to 'std::vector::size_type' (aka 'unsigned long') [-Wfloat-conversion]
          const unsigned int current_section = (unsigned int)std::floor(one_dimensional_coordinates[distance_from_planes["section"]]);
                                                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../contrib/WorldBuilder/source/features/subducting_plate.cc:476:101: warning: implicit conversion turns floating-point number into integer: 'std::map<std::__cxx11::basic_string<char>, double, std::less<std::__cxx11::basic_string<char> >, std::allocator<std::pair<const std::__cxx11::basic_string<char>, double> > >::mapped_type' (aka 'double') to 'std::vector::size_type' (aka 'unsigned long') [-Wfloat-conversion]
          const unsigned int current_section = (unsigned int)std::floor(one_dimensional_coordinates[distance_from_planes["section"]]);
                                                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2 warnings generated.
[192/193] Building CXX object CMakeFiles/aspect.dir/contrib/WorldBuilder/source/utilities.cc.o
../contrib/WorldBuilder/source/utilities.cc:512:57: warning: implicit conversion turns floating-point number into integer: 'double' to 'const unsigned int' [-Wfloat-conversion]
          const unsigned int original_current_section = std::floor(global_x_list[i_section]);
                             ~~~~~~~~~~~~~~~~~~~~~~~~   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../contrib/WorldBuilder/source/utilities.cc:762:107: warning: implicit conversion turns floating-point number into integer: 'const double' to 'std::vector::size_type' (aka 'unsigned long') [-Wfloat-conversion]
                  const double interpolated_angle_top    = plane_segment_angles[original_current_section][current_segment][0]
                                                           ~~~~~~~~~~~~~~~~~~~~                           ^~~~~~~~~~~~~~~
../contrib/WorldBuilder/source/utilities.cc:763:127: warning: implicit conversion turns floating-point number into integer: 'const double' to 'std::vector::size_type' (aka 'unsigned long') [-Wfloat-conversion]
                                                           + fraction_CPL_P1P2 * (plane_segment_angles[original_next_section][current_segment][0]
                                                                                  ~~~~~~~~~~~~~~~~~~~~                        ^~~~~~~~~~~~~~~
../contrib/WorldBuilder/source/utilities.cc:764:132: warning: implicit conversion turns floating-point number into integer: 'const double' to 'std::vector::size_type' (aka 'unsigned long') [-Wfloat-conversion]
                                                                                  - plane_segment_angles[original_current_section][current_segment][0])
                                                                                    ~~~~~~~~~~~~~~~~~~~~                           ^~~~~~~~~~~~~~~
../contrib/WorldBuilder/source/utilities.cc:767:107: warning: implicit conversion turns floating-point number into integer: 'const double' to 'std::vector::size_type' (aka 'unsigned long') [-Wfloat-conversion]
                  const double interpolated_angle_bottom = plane_segment_angles[original_current_section][current_segment][1]
                                                           ~~~~~~~~~~~~~~~~~~~~                           ^~~~~~~~~~~~~~~
../contrib/WorldBuilder/source/utilities.cc:768:127: warning: implicit conversion turns floating-point number into integer: 'const double' to 'std::vector::size_type' (aka 'unsigned long') [-Wfloat-conversion]
                                                           + fraction_CPL_P1P2 * (plane_segment_angles[original_next_section][current_segment][1]
                                                                                  ~~~~~~~~~~~~~~~~~~~~                        ^~~~~~~~~~~~~~~
../contrib/WorldBuilder/source/utilities.cc:769:132: warning: implicit conversion turns floating-point number into integer: 'const double' to 'std::vector::size_type' (aka 'unsigned long') [-Wfloat-conversion]
                                                                                  - plane_segment_angles[original_current_section][current_segment][1])
                                                                                    ~~~~~~~~~~~~~~~~~~~~                           ^~~~~~~~~~~~~~~
../contrib/WorldBuilder/source/utilities.cc:773:108: warning: implicit conversion turns floating-point number into integer: 'const double' to 'std::vector::size_type' (aka 'unsigned long') [-Wfloat-conversion]
                  double interpolated_segment_length     = plane_segment_lengths[original_current_section][current_segment]
                                                           ~~~~~~~~~~~~~~~~~~~~~                           ^~~~~~~~~~~~~~~
../contrib/WorldBuilder/source/utilities.cc:774:128: warning: implicit conversion turns floating-point number into integer: 'const double' to 'std::vector::size_type' (aka 'unsigned long') [-Wfloat-conversion]
                                                           + fraction_CPL_P1P2 * (plane_segment_lengths[original_next_section][current_segment]
                                                                                  ~~~~~~~~~~~~~~~~~~~~~                        ^~~~~~~~~~~~~~~
../contrib/WorldBuilder/source/utilities.cc:775:133: warning: implicit conversion turns floating-point number into integer: 'const double' to 'std::vector::size_type' (aka 'unsigned long') [-Wfloat-conversion]
                                                                                  - plane_segment_lengths[original_current_section][current_segment]);
                                                                                    ~~~~~~~~~~~~~~~~~~~~~                           ^~~~~~~~~~~~~~~
10 warnings generated.
```

**Comment by MFraters** [comment]
could you try again?

**Comment by tjhei** [comment]
this works for me. :+1:

**Comment by MFraters** [comment]
Great! Do you need it now in aspect, or can it wait for the removal of the submodule?

**Comment by tjhei** [comment]
> Great! Do you need it now in aspect, or can it wait for the removal of the submodule?

Not super urgent. Let's discuss with Rene and Wolfgang about putting the code in.

**Pull request merged**
