### PR TITLE
Random uniform distribution deflected as rotation with tests

### PR DESCRIPTION
**Pull request by Wang-yijun**
Generated= random uniform distribution with a deflection as rotations and apply these rotations to an input orientation represented with Euler angle or rotation matrix. This grain model is added for all features.
I also removed the old tests for this grain model random_uniform_distribution_deflected using two different random number seed and added new tests.
Some sample generated textures (plotted using MTEX in Matlab):
Input Euler angle (0,0,0), deflection=0.001
shearbox_test_0_0_0_0 001
Input Euler angle (0,0,0), deflection=1
shearbox_test_0_0_0_1
Input Euler angle (0,90,0), deflection=0.001
shearbox_test_0_90_0_0 001
Input Euler angle (90,90,0), deflection=0.001
shearbox_test_90_90_0_0 001

### CODE REVIEW

**Comment by Wang-yijun** [comment]
More examples on textures with 10,000 grains (plotted with MTEX default colormap in Matlab):
Input Euler angle (0,90,0), deflection=0.001
shearbox_test_0_90_0_0 001
Input Euler angle (0,90,0), deflection=0.1
shearbox_test_0_90_0_0 1
Input Euler angle (0,90,0), deflection=0.3
shearbox_test_0_90_0_0 3
Input Euler angle (0,90,0), deflection=0.6
shearbox_test_0_90_0_0 6
Input Euler angle (0,90,0), deflection=0.9
shearbox_test_0_90_0_0 9
Input Euler angle (0,90,0), deflection=1
shearbox_test_0_90_0_1

**Review by MFraters — COMMENTED** [review]
Looks good, thanks for the changes! Great to see that you also added a plume version. I need to look a bit more into some of the code, but here are already some comments.

1. I think it would make sense to move the `matrix_multiply` function to a utilities function `multiply_3x3_matrices` or something similar. 
2. Add a unit test for the matrix multiply function to make sure that it works as expected.

**Comment by MFraters** [comment]
> More examples on textures with 10,000 grains (plotted with MTEX default colormap in Matlab): ....

This looks great, thanks!

**Comment by Wang-yijun** [comment]
I've moved the matrix_multiply functions in grain model features into utilities and made a unit test for it.

**Comment by MFraters** [comment]
Some testers fail because `std::transform` is a c++17 feature, and currently the world builder is a c++14 code. Can you rewrite it in a c++14 way and maybe leave as a comment that once we switch to c++17 we can update it.

**Comment by Wang-yijun** [comment]
I've changed std::transform to for loops.

**Review by MFraters — APPROVED** [review]
Thanks! It looks good to me now. Please squash the commits as discussed and then it should be ready to merge.

**Comment by MFraters** [comment]
Based on the coverage results, it looks like there is no test for `random_uniform_distribution_deflected`. Could you add that?

**Comment by Wang-yijun** [comment]
The tests I added are called "random_uniform_distribution_deflected_asrotation_seed1.wb" and "random_uniform_distribution_deflected_asrotation_seed1000.wb". Is this the reason that the tests are not detected?

**Comment by MFraters** [comment]
The tests are run, see https://github.com/GeodynamicWorldBuilder/WorldBuilder/actions/runs/9373443402/job/25807253224?pr=713, but they do not cover the that part of the code. I also just noticed that some comments have not been addressed, can you take another look at them?

**Comment by Wang-yijun** [comment]
I might have messed up the commits with squash. I've fixed the plume test and addressed the comments above now.

**Comment by Wang-yijun** [comment]
I've added tests to use rotation matrices for initial textures to improve the coverage.

**Review by MFraters — APPROVED** [review]
Great, thanks for also fixing the coverage! One more thing, can you add a changelog entry in Changelog.md?

**Comment by Wang-yijun** [comment]
Done!

**Review by MFraters — APPROVED** [review]
Thanks!

**Pull request merged**
