### PR TITLE
Remove static header variable

### PR DESCRIPTION
**Pull request by MFraters**
The solution for having a plugin system has been reported to cause problems with gcc 5 (#118 and see geodynamics/aspect#2613). Doing some more research on a different solution, I am now testing whether a linker flag (-Wl,--whole-archive) might also solve the problem of non-referenced compiler units causing the plugin system to fail. This solution might even better, because it will fully automatize the plugin system.

(re-pull request from #119, had incorrectly setup remote in new clone)

### CODE REVIEW

**Comment by tjhei** [comment]
What are you trying to do with these variables? The ``whole-archive`` flag is mostly used for static libraries, how do you think this will fix the issue?

**Comment by MFraters** [comment]
The fundemental problem I am trying to solve is explained here: https://stackoverflow.com/questions/5202142/static-variable-initialization-over-a-library. For aspect there is no problem, because it compiles  the code directly. But the world builder is also (actually mostly) designed to be used as a library. Because I used the solution in the last post on that page, I got an unused variable. 

Doing a bit more digging, I found that there is also a linker variable which forces the linking of the whole library (and thereby the automatic registration). This solution seems to work on linux, osx and windows on travis, but in appveyor it gives a linking error static that there are multiple definitions of std library functions like vector and new. I tried to see whether making the windows environment on appveyor more like travis solves the problem, but it doesn't. So I am for now also adding a windows release test on travis (used to be only debug).

**Comment by tjhei** [comment]
> The fundemental problem I am trying to solve is explained here:

Is the program not referencing anything in the worldbuilder library or what is the issue?

Maybe a simpler solution is to have a ``WorldBuilder_Initialize()`` or something like this that the user needs to call?

**Comment by MFraters** [comment]
This is what I understand the problem to be. To auto register all the plugins they need to be added to some kind of static variable. In a normal program it initializes all the static variables before the program start, thereby giving the program the opportunity to auto register the plugins. For a library, static variables are not automatically initialized/included, only when they are implicitly or explicitly referenced in every compilation unit. So to auto register plugins, I need to make sure every plugin is actually 'used', in order for it to be included. That is what the code did and gave the warning, because the 'use' of the plugin may not actually do anything. 

The approach I am now are going for is telling the compiler that it actually has to include the whole library, and that way it will initialize the static variables and auto register the plugins. This method is actually better since with the previous method, the registration was not fully automatic and the code is cleaner now. 

Also I seem to have fixed the problem in appveyor :)

**Comment by MFraters** [comment]
@tjhei Do you have an alternative solution?
Since the problems with the testers seem to be fixed, I will start removing all the unused static variables and make a pull request to update the world builder code in aspect.

**Comment by tjhei** [comment]
> Do you have an alternative solution?

I do not, sorry. If this works for you, sure, go ahead. 

Long term you might need to think about something that is less complicated for the user?

**Comment by MFraters** [comment]
So for aspect the `whole-archive` is not needed, because it is compiled directly. So there should be no change for aspect. For the codes which use the library, they need to add two more linking flags. If they want to support osx, then they need will need a seperate case for that and add one flag (different) instead of two. I will document that, so it shouldn't be too hard not I have figured out how to do it.

Although I also want a more user friendly approach, from reading about this problem, I have the feeling that it is quite fundamental to how cpp libraries work at a minimum (it may differ per compiler what is done exactly I think). The method I used before seemed to work good enough, and I am still a bit surprised that it gave those warnings for gcc 5, because with gcc 8 and the intel compiler I didn't see those warnings, as well as with gcc 4.9 and gcc 6 which is used by the world builder tester, which also tests linking the world builder to an application. Since the new solution should solve the problem for gcc 5, I a fine with changing to this solution

**Comment by tjhei** [comment]
> I am still a bit surprised that it gave those warnings for gcc 5, because with gcc 8 and the intel compiler I didn't see those warnings

yeah, problems like this are annoying. :-( Thanks for working on a fix!

**Comment by MFraters** [comment]
@tjhei I have tested this version of the world builder with the docker instructions you gave and I don't see the warnings anymore. 

I have updated (and retested) the documentation as well, and it should be ready to merge when the testers pass.

**Pull request merged**
