### PR TITLE
Add a simple subduction 2d chunk model cookbook

### PR DESCRIPTION
**Pull request by mibillen**
This pull request address issue #535, case 2 although I decided to keep this cook book simpler, so it does not include a location specific model of points from slab 2.0.  It does however, several small but tricky things about making 2D models in the spherical/chunk geometry.

### CODE REVIEW

**Review by gassmoeller — COMMENTED** [review]
Very nice, thanks for the detailed explanation (my way of learning the world builder is to review everyone's pull requests :-)).
One question about the paraview state files, everything else is just minor typos.

**Comment by MFraters** [comment]
@mibillen I think you forgot the check in `/cookbooks/simple_subduction_2d_chunk/simple_subduction_2d_chunk.grid`. The tester need that to test the world builder file.

**Comment by mibillen** [comment]
I've added the missing file ... the needed file was there, but it had a different name. I committed and then "squashed" :-)

**Review by MFraters — APPROVED** [review]
Great, cookbook, thanks for writing this! It i very detailed and leads the user through your thought process in setting up this model. I also like that you put some try yourself exercises at the end :)

I found a few more of Rene's suggestions which for some reason didn't show up in the conversations page, but did in the files changed. They looked uncontroversial to me, so I just merged them.

**Pull request merged**
