### PR TITLE
gwb-grid: support for filtering cells

### PR DESCRIPTION
**Pull request by tjhei**
Add a new option --by-tag that enables filtering of cells inside gwb-grid. To actually do something useful, we need support inside GWB to provide tag information. So, right now, this option randomly selects some cells to be shown.

### CODE REVIEW

**Comment by tjhei** [comment]
This is ready for review @MFraters

**Review by MFraters — APPROVED** [review]
I have some questions about the structure, but that is probably because it is not actually using the tags yet. I think it is probably best to merge it as is, and then we can discuss those things when it is ready to do the actual filtering.

**Comment by MFraters** [comment]
Or do you want to do everthing in this pull request, given that it is still marked as [wip]?

**Comment by tjhei** [comment]
Let me make a few updates...

**Comment by tjhei** [comment]
Okay, this is now ready to review and merge. I do not advertise the new option in ``--help`` yet, because it only filters tag -1 for now. I will follow up with additional PRs later. @MFraters

**Pull request merged**
